alias vs="cd $VAGRANT_PATH && vagrant status"
alias vu="cd $VAGRANT_PATH && vagrant up"
alias vp="cd $VAGRANT_PATH && vagrant provision"
alias vh="cd $VAGRANT_PATH && vagrant halt"
alias vssh="cd $VAGRANT_PATH && vagrant ssh"
